### ISSUE TITLE
Can you share some stats that this works ?

### ISSUE THREAD

**Issue by jalotra** [sahilbansal17/Get_Better_at_CP_in_2_Months#9]

**Comment by sahilbansal17** [comment]
@jalotra This is just a repository that contains collection of problems that you can try to solve in 2 months time frame, you need to put persistent efforts, that being said you can't become a CP expert in just 2 days of practice.

You can try anything similar, like CCDSAP practice section, CP books by Steven Halim, IOI Practice Sheet, Junior Training Sheet, anything else that you can find here: [Awesome CP list](https://github.com/lnishan/awesome-competitive-programming) but the success will depend on the quality of the efforts put in by you 👍

**Comment by jalotra** [comment]
@sahilbansal17  Thanks for the advice and resources.
